import Head from "next/head";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const Layout = ({ children }: any) => {
    return (
        <>
            <Head>
                <title>Malaya Speech Prototype</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
                {/* <meta
                    http-equiv="Content-Security-Policy"
                    content="upgrade-insecure-requests"
                /> */}
            </Head>
            <Toaster />
            <div className="navbar bg-base-100 shadow-md">
                <div className="navbar-start">
                    <Link href={"/"}>
                        <a className="btn-ghost btn text-xl normal-case">
                            malaya<span className="text-primary">Speech</span>
                        </a>
                    </Link>
                </div>
            </div>
            {children}
        </>
    );
};

export default Layout;
